# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userMessage',
            fields=[
                ('object_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('message', models.CharField(max_length=500, verbose_name='留言板')),
            ],
            options={
                'verbose_name': '用户留言信息',
                'verbose_name_plural': '用户留言信息',
            },
        ),
    ]
